name: CI

on: push

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.APTO_BOT_TOKEN }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
