name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.APTO_BOT_TOKEN }}

      - name: Set npm token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - name: Set git email
        run: git config user.email "aptobot.fe@aptopayments.com"

      - name: Set git name
        run: git config user.name "AptoBotFe"

      - name: Install
        run: npm ci

      - name: Release
        run: npm run release

      - name: Publish
        run: git push --follow-tags origin main && npm publish
